### ISSUE TITLE
[Bug]: modern build failed on windows10 but work successfully on windows11 and macOS

### ISSUE THREAD

**Issue by AuglyXu** [web-infra-dev/modern.js#4883] opened 2023-10-30 07:07 UTC
### Version

```sh
System： windows10
version: 2.39.0
```

### Details

我的配置如下：
import { moduleTools, defineConfig } from '@modern-js/module-tools';

export default defineConfig({
	buildConfig: [
		{
			format: 'cjs',
			target: 'es6',
			buildType: 'bundleless',
			outDir: './build/lib',
			sideEffects: [/\.css$/],
			dts: false,
			/** 只需拷贝一次即可 */
			copy: {
				patterns: [
					{
						from: 'package.json',
						context: __dirname,
						to: './../package.json',
					},
				],
			},
		},
		{
			format: 'esm',
			target: 'es6',
			buildType: 'bundleless',
			outDir: './build/es',
			sideEffects: [/\.css$/],
			dts: false,
		},
	],
	plugins: [moduleTools()],
});

### Reproduce link

base config enough

### Reproduce Steps

![image](https://github.com/web-infra-dev/modern.js/assets/42527305/ed3e778f-4830-4209-a4a2-6afb8eec948f)
![image](https://github.com/web-infra-dev/modern.js/assets/42527305/bac9516e-7014-40d8-9f8f-612d92187638)

**Comment by chenjiahan** [comment] 2023-10-31 05:59
@10Derozan Please check this

**Comment by 10Derozan** [comment] 2023-10-31 08:17
重装依赖可以解决吗

**Comment by AuglyXu** [comment] 2023-10-31 09:44
> 重装依赖可以解决吗

解决不了诶

**Comment by 10Derozan** [comment] 2023-10-31 10:23
我理解这是本地环境的问题吧，可以提供一些解答么？感谢@HerringtonDarkholme

**Comment by fengjiling123** [comment] 2023-11-01 08:56
@10Derozan 把buildType: 'bundleless'改成buildType: 'bundle'就好了，麻烦看一下为什么bundleless会报这个错

**Comment by fengjiling123** [comment] 2023-11-01 09:06
@10Derozan 把demo的配置改成你npm-component也会报这个错
![image](https://github.com/web-infra-dev/modern.js/assets/31927435/09242e05-774b-49de-ae95-99674643a37f)

**Comment by HerringtonDarkholme** [comment] 2023-11-01 09:08
Hey @AuglyXu can you list the content inside node_modules of @ast-grep. Probably we need all directories inside there.

**Comment by HerringtonDarkholme** [comment] 2023-11-01 09:11
I can see napi's node binding in the npm package. Is it caused by pnpm + windows?
<img width="901" alt="image" src="https://github.com/web-infra-dev/modern.js/assets/2883231/b3c84feb-3194-4a18-b1d8-ed20ff2f0ffc">

**Comment by AuglyXu** [comment] 2023-11-01 09:45
![image](https://github.com/web-infra-dev/modern.js/assets/42527305/dc4fb82e-7e9d-4777-9033-ba427ad750ce)
Is this what you want to see?
It is caused by pnpm + windows.

**Comment by AuglyXu** [comment] 2023-11-01 09:45
> I can see napi's node binding in the npm package. Is it caused by pnpm + windows? <img alt="image" width="901" src="https://user-images.githubusercontent.com/2883231/279628040-b3c84feb-3194-4a18-b1d8-ed20ff2f0ffc.png">

![image](https://github.com/web-infra-dev/modern.js/assets/42527305/dc4fb82e-7e9d-4777-9033-ba427ad750ce)
Is this what you want to see?
It is caused by pnpm + windows.

**Comment by HerringtonDarkholme** [comment] 2023-11-01 20:31
@AuglyXu can you try  these commands in a **new** project?  https://ast-grep.github.io/guide/api-usage.html

```bash
pnpm add @ast-grep/napi
```

```js
import { js } from '@ast-grep/napi';

const source = `console.log("hello world")`
const ast = js.parse(source)
const node = ast.root().find('console.log')
```

If the code example works, I would speculate the problem is pnpm.

**Comment by HerringtonDarkholme** [comment] 2023-11-01 21:12
@AuglyXu I think there is some issues in your deps. 

pnpm is finding ast-grep/napi 0.12.0

![image](https://github.com/web-infra-dev/modern.js/assets/2883231/c24140ee-b932-486d-984a-9fd3098562e6)

while modern only installs 0.1.13

![image](https://github.com/web-infra-dev/modern.js/assets/2883231/be6a3e8c-2ab5-4c53-8638-bae2be392e1a)

**Comment by AuglyXu** [comment] 2023-11-02 05:15
> @AuglyXu I think there is some issues in your deps.
> 
> pnpm is finding ast-grep/napi 0.12.0
> 
> ![image](https://user-images.githubusercontent.com/2883231/279803670-c24140ee-b932-486d-984a-9fd3098562e6.png)
> 
> while modern only installs 0.1.13
> 
> ![image](https://user-images.githubusercontent.com/2883231/279803878-be6a3e8c-2ab5-4c53-8638-bae2be392e1a.png)

Thank you @HerringtonDarkholme .Actually it not append on my computer, it's my partner's computer happened.My partner firmly believe that I pasted the wrong picture and she proposed the new issue [https://github.com/web-infra-dev/modern.js/issues/4900](url), so she unwilling to try and i'm also distressed.She say may be you can position from the new picture.Does she need to run the above code or you can position the question combined the two pictures？

**Comment by 10Derozan** [comment] 2023-11-03 02:42
> @10Derozan 把buildType: 'bundleless'改成buildType: 'bundle'就好了，麻烦看一下为什么bundleless会报这个错

bundleless 的场景我才会用 ast-grep 做一些例如别名替换的操作

**Comment by 10Derozan** [comment] 2023-11-03 03:00
I recommend you can follow the steps below: 
1. Check the package version. Now modern.js use ast-grep@0.12.0, please use the latest modern.js and reinstall.
2. Then check the node_modules, you had better add a screenshot about @ast-grep in node_modules.
3. If the version is right, and win32-x64-msvc.node exist,  use ast-grep directly,  and follow [the tips](https://github.com/web-infra-dev/modern.js/issues/4883#issuecomment-1789633105),  check the same error or not.

It doesn't look like it's an ast grep problem. If you can not reappear, i'll close this issue two days later

> > @AuglyXu I think there is some issues in your deps.
> > pnpm is finding ast-grep/napi 0.12.0
> > ![image](https://user-images.githubusercontent.com/2883231/279803670-c24140ee-b932-486d-984a-9fd3098562e6.png)
> > while modern only installs 0.1.13
> > ![image](https://user-images.githubusercontent.com/2883231/279803878-be6a3e8c-2ab5-4c53-8638-bae2be392e1a.png)
> 
> Thank you @HerringtonDarkholme .Actually it not append on my computer, it's my partner's computer happened.My partner firmly believe that I pasted the wrong picture and she proposed the new issue [https://github.com/web-infra-dev/modern.js/issues/4900](url), so she unwilling to try and i'm also distressed.She say may be you can position from the new picture.Does she need to run the above code or you can position the question combined the two pictures？

**Comment by 10Derozan** [comment] 2023-11-03 03:02
Ok ,fine, i found another issue the same with this, switch there.

**Closed by 10Derozan** 2023-11-03 03:02 UTC
Labels: bug
